### ISSUE TITLE
Enable github discussions?

### ISSUE THREAD

**Issue by infogulch** [magmide/magmide#11]
Hi! I like the ideas in the posts you've published here.

As I've been reading I've had some thoughts or questions pop up, but it felt off to open an issue about it because issues carry some additional baggage such as the expectation of a response, the implication that it requires some action, and the decision to close, none of which would align with my intent to simply comment. I've observed this mismatch in other issues as well.

Perhaps such commentary would be better packaged by Discussions. What do you think about enabling the Discussions repository feature? Or more generally, do you have plans for building a community around magmide? (chat, forums, meetups, etc)

**Comment by blainehansen** [comment]
Done :) Thanks for making me aware of that feature!
