### ISSUE TITLE
Typos in `intro-verification-logic-in-magmide.md`

### ISSUE THREAD

**Issue by MartinKavik** [magmide/magmide#14]
Hi, this is very interesting project! 
I've just found these small "typos" in `intro-verification-logic-in-magmide.md`:

1.
    ```magmide
    // standard signed and unsigned integers
    let unsigned_8_bits: u8 = 0    // should be `let signed_8_bits: i8 = 0`
    let unsigned_8_bits: u8 = 0
    ```
    ([src](https://github.com/magmide/magmide/blob/12617d75a870ed8d3011706dfcb7b7f710cdb3b1/posts/intro-verification-logic-in-magmide.md?plain=1#L387))

2.
    ```magmide
    alias Range; i32, i32 & > ^.1    // should be  `alias Range; i32, i32 & > ^.0`
    ```
    ([src](https://github.com/magmide/magmide/blob/12617d75a870ed8d3011706dfcb7b7f710cdb3b1/posts/intro-verification-logic-in-magmide.md?plain=1#L478))

Can I create a PR?

**Comment by blainehansen** [comment]
Honestly I shouldn't even be telling people to read the tutorial posts ha, they're so rough and work-in-progress.

But just to make you happy, I fixed them :) Barely worth a whole pr.
