### ISSUE TITLE
Please add a donate button

### ISSUE THREAD

**Issue by BGordts** [magmide/magmide#19]
Love this idea! I think the vision is truly compelling and worth the bet. Coming from the Web3 industry, I believe this project can play a big role in making more secure smart contracts, and I believe a good audience to target as early adopters. Also there’s money there, and a strong culture of funding public goods.

Can you please add a donate button so that people can help out even if they don’t have time? Also, I think this could be a great project for https://gitcoin.co/grants/.

**Comment by blainehansen** [comment]
Thank you for being willing to give support! Unfortunately, it's a little complicated, and I've given a more thorough explanation in a FAQ entry:
https://github.com/magmide/magmide#will-you-provide-a-way-to-accept-financial-contributions

I'm pretty sure gitcoin grants aren't "all or nothing" in the same way something like a kickstarter campaign is right? For me that would be a problem. Perhaps I'm being too picky, but I have more people in my life to worry about than myself, so I'm a bit hesitant to take open-ended financial risks.

Thank you again though!
