### ISSUE TITLE
Comparison with TLA+

### ISSUE THREAD

**Issue by dlukes** [magmide/magmide#2]
I'm just a curious onlooker in the field of formal verification of software (basically purely by virtue of having subscribed to Hillel Wayne's newsletter), so most of the README is way above my paygrade. However, even with my very superficial knowledge, I was expecting a comparison with [TLA+](https://lamport.azurewebsites.net/tla/tla.html) (see also <https://www.learntla.com/>), which has already been [adopted by some parts of the industry](https://lamport.azurewebsites.net/tla/industrial-use.html) where correctness is critical or can save a lot of money.

Since Magma also has the ambition to improve real-world software projects, a comparison with TLA+ would be helpful. What does Magma plan to bring to the table that TLA+ doesn't offer? Does it have a broader scope that encompasses TLA+'s and adds more? Or would they essentially be complementary tools?

**Comment by blainehansen** [comment]
In general yes TLA+ is much more specific than a general purpose higher-order logic like what Coq uses, so something like TLA+ could be implemented *within* Coq or Magma.

I've been meaning to add an explicit "comparison with X" section to address all of these cases ha. Thanks for reminding me of TLA+!

**Comment by dlukes** [comment]
> so something like TLA+ could be implemented within Coq or Magma

Ah, gotcha :) Thanks, that's helpful!

**Comment by blainehansen** [comment]
Closed by https://github.com/magmide/magmide/commit/f8642fb19851745089f2636e6cbfc07f31f1ac50
:)

**Comment by dlukes** [comment]
Thanks for the heads up!
