### ISSUE TITLE
Can you evaluate ATS?

### ISSUE THREAD

**Issue by hungrymonkey** [magmide/magmide#20]
ATS is a kinda a scary language. How your project differs from this proof writing language. This language tops the programming benchmark chart until it was removed because there isn't enough experts in the language

https://www.youtube.com/watch?v=zt0OQb1DBko

https://github.com/githwxi/ATS-Xanadu

https://github.com/magmide/magmide/blob/main/posts/comparisons-with-other-projects.md

https://stackoverflow.com/questions/26958969/why-was-the-ats-language-dropped-from-the-computer-language-benchmarks-game

https://ats-lang.github.io/DOCUMENT/INT2PROGINATS/PDF/main.pdf

Can you evaluate the language?

I personally have never written hello world in this language.

**Comment by blainehansen** [comment]
I spent some watching that video and reading the docs, and I've added a section to the comparison page:
https://github.com/magmide/magmide/blob/main/posts/comparisons-with-other-projects.md

Let me know if you think I misunderstood or missed something important :)
