### ISSUE TITLE
Research debt for contributors

### ISSUE THREAD

**Issue by jgarvin** [magmide/magmide#21]
I've spent a good amount of time thinking about how the world would be changed by more reliable software and how I wish more languages tried to push the frontier instead of just picking new points on the Pareto curve. Rust's attempt to get improved safety without performance sacrifices is the best recent example of a language both doing this and aiming for mainstream acceptance. Magmide looks like it's trying to do that on steroids, so there is a lot in the README for me to agree with and get excited about even if there's nothing concrete yet.

However, as you pointed out research debt makes a lot of this inaccessible. How would you suggest people with similar goals or would-be contributors get up to speed? This is assuming people in the target audience for the final product: experienced imperative programmers without any familiarity with the advances in the academic world, so no knowledge of Coq/Agda/Iris/dependent-types/formal-logic etc. Since it's a goal to make something they would find accessible it seems like figuring out how to inform possible contributors could overlap with figuring out how to make the language more easily learnable.

**Comment by blainehansen** [comment]
I've shared some resources here :)
https://github.com/magmide/magmide#this-is-an-exciting-idea-how-can-i-help

I've been toying with spinning out a related project, something like "Coq for Engineers", and have some scribbling about it here:
[`posts/coq-for-engineers.md`](./posts/coq-for-engineers.md)

I've had to focus on my day job and family things for the past few months though. Hopefully I get more time to think about Magmide soon.
