### ISSUE TITLE
Avoid Sisyphus trap

### ISSUE THREAD

**Issue by vvs-** [magmide/magmide#23]
Hello,

While reading a comparison of this project goals with other existing languages I was somewhat appalled by a misjudgement about Lean in particular, which I'm happened to be familiar with. Believe me, that comparison missed target on most points: Lean is not developed in academy, it's targeted for practical software development by Microsoft, it is developed by engineers and for engineers as well, it's not interpreted language, also its metaprogramming model was partially inspired by Racket and Rust if that matters. AFAIK there are even plans to support Iris in the future. But it's true that Lean is a pure functional programming language (like Haskell), though it does have some innovative "imperative"-like constructs and optimizations. Also, it's true that Lean 4 is in early development stages and it is still mostly adopted for formalizing mathematics at the moment.

Of course, don' trust my words on this, I'm not an expert myself. But to avoid poor judgement and probably before wasting some of your efforts, I would sincerely suggest to ask opinion of Lean developers and experts in these matters, e.g. https://leanprover.zulipchat.com I'm sure they will be happy to discuss it with you. Please, bear in mind that Lean 3 (stable version) and Lean 4 are quite different and incompatible languages! Also mathlib is not Lean and they should not be confused!

**Comment by blainehansen** [comment]
Feel free to take this to a discussion. I can be convinced Lean is closer than I think to Magmide's goal, but you'll have to be more specific.

**Comment by vvs-** [comment]
That wasn't my goal. I've just tried to point out that that comparison was based on dubious or obsolete arguments. Leaving that text as it is still looks misleading. I thought that you might be interested in improving it. And honestly, I don't see any benefit for anyone if it was me trying to start discussion on that topic with Lean developers. I'm not involved with this project, so why should it be proxyed this way?

BTW, if you really wanted to compare apples to apples, comparing with well-known industrial solutions like SPARK 2014 and Frama-C would look more appropriate.

Best regards.
