### ISSUE TITLE
Building the community

### ISSUE THREAD

**Issue by serid** [magmide/magmide#24]
Github Discussions and Issues are a good way to coordinate contributors and manage code development. However I think it would be nice to have a Discord server or a Telegram chat to talk about language design topics like type theory, software verification, programming patterns and other general ideas not directly related to code and implementation. Is there anything similar to that?

**Comment by serid** [comment]
A good example of such community platform would be [Rust Discord](https://discord.gg/TKJkrBUrEH) and [Rust Zulip Chat](https://rust-lang.zulipchat.com/).

**Comment by blainehansen** [comment]
When the project is a little more developed and has more momentum we can start thinking about building the community. For now it seems premature to spread the word much further when there's not much to see!

I'm going to write up a brief "what's next for magmide" post tomorrow, discussing how we can make progress even while I'm busy. Stay tuned for that :)

**Comment by serid** [comment]
Thank you for your reply! Looking forward to the post

**Comment by blainehansen** [comment]
https://github.com/magmide/magmide/discussions/25 :)
