### ISSUE TITLE
wtf is this and how will it make my life easier?

### ISSUE THREAD

**Issue by Kreyren** [magmide/magmide#27]
the readme is long af and the more i look at the source code the more confused i get.. ehh can someone explain it to me?

**Comment by oskgo** [comment]
Currently this is mostly a bunch of ideas and experiments.

The ideas are for a tool that helps you prove things about the programs you write. There's a bunch of such tools out there already, but this one aims to have tight integration between a low level imperative implementation language and a powerful specification language. Other tools with low level implementation languages tend to have it "tacked on" or externally defined or have a weak specification language.

**Comment by blainehansen** [comment]
Sorry @Kreyren, the readme is long because this is a complex topic with lots to say! And the first line explains that the code isn't really in a shareable state: 
> This repo is still very early and rough, it's mostly just notes, speculative writing, and exploratory theorem proving. Most of the files in this repo are just "mad scribblings" that I haven't refined enough to actually stand by!

There's a video if that makes things better.
https://www.youtube.com/watch?v=Lf7ML_ErWvQ
